name: 'Composite action JS'
description: 'Testando composite action'

inputs:
  my-input:
    description: 'Input pego pelo testing-composite'
    required: true
    default: 'world'
  outputs:
    my-output:

runs:
  using: 'node20'
  main: 'index.js'

