name: 'Composite action'
description: 'Setup, install dependencies'

inputs:
  my-input:
    description: 'Input"
    required: true
    default: ''
  runs:
    using: 'composite'
    
    steps:
      - name: Hello ${{ inputs.my-input }} 
        run: echo "Hello ${{ inputs.my-input}}!"
        shell: bash
