name: 'Composite action'
description: 'Testando composite action'

inputs:
  my-input:
    description: 'Input pego pelo testing-composite'
    required: true
    default: 'world'
  outputs:
    my-output:
      description: 'Output'
      value: ${{ steps.hello-world-msg.outputs.output }}
runs:
  using: 'composite'
  steps:
    - name: Hello ${{ inputs.my-input }}
      run: echo "Hello ${{ inputs.my-input }}!"
      shell: bash

    - name: Send Output
      id: hello-world-msg
      run: echo "output=$(echo Hello ${{ inputs.my-input }})" >> $GITHUB_OUTPUT
