name: 'Composite action'
description: 'Testando composite action'

inputs:
  my-input:
    description: 'Input'
    required: true
    default: 'world'

runs:
  using: 'composite'
  steps:
    - name: Hello ${{ inputs.my-input }}
      run: echo "Hello ${{ inputs.my-input }}!"
      shell: bash
