name: Conditionals

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deploy to Production Server
        id: deploy-production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Deploying to production server..."
        shell: bash
        
      - name: Deploy to Develop Server
        id: deploy-develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo "Deploying to develop server..."
        shell: bash

      - name: Production Status
        if: ${{ github.ref == 'refs/heads/main' &&  steps.deploy-production.conclusion == 'success' }}
        run: echo "Deployed successfully to production server!"

      - name: Development Status
        if: ${{ github.ref == 'refs/heads/develop' &&  steps.deploy-develop.conclusion == 'success' }}
        run: echo "Deployed successfully to development server!"

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cleaning Server Artifacts Cache
        run: echo "Cleaning artifacts..."
        shell: bash
