name: Deploy develop

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Deploy develop Server
              run: echo "Deploying to develop server..."
              shell: bash