name: Deploy Production

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Deploy Production Server
              run: echo "Deploying to production server..."
              shell: bash