on: [ push ]

jobs: 
  hello_world_job:
    name: New Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello
        uses: JvictorMarques/workflow@v1
        id: hello-world
        with:
          my-input: world
